set(CPACK_GENERATOR "DEB")

set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Siegfried Nowhere <siegfried.artworks@gmail.com>")
set(CPACK_DEBIAN_PACKAGE_VENDOR "Siegfried")

set(CPACK_DEBIAN_PACKAGE_DESCRIPTION "Test-001")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
# set(CPACK_DEBIAN_PACKAGE_DEPENDS "paquete01 (>= 2.1.1), paquete02 (>= 1.0.0)")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "required")
set(CPACK_PACKAGE_NAME "${PROJECT_NAME}")
set(CPACK_PACKAGE_VERSION "${TEST001_VERSION_STR}")
set(CPACK_PACKAGE_VERSION_MAJOR "${TEST001_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${TEST001_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${TEST001_VERSION_REVISION}")
# set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${CMAKE_CURRENT_SOURCE_DIR}/recursos/postinst;${CMAKE_CURRENT_SOURCE_DIR}/recursos/postrm;${CMAKE_CURRENT_SOURCE_DIR}/recursos/prerm;")

include(CPack)
